apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-app
  labels:
    app: go-hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-hello-app
  template:
    metadata:
      labels:
        app: go-hello-app
    spec:
      containers:
      - name: go-hello-app
        image: yourdockerhubusername/go-hello-app:latest # Replace with your image
        ports:
        - containerPort: 8081
