apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of resources to manage with Kustomize
resources:
  - nodejs-deployment.yaml
  - nodejs-service.yaml
  - go-deployment.yaml
  - go-service.yaml

images:
- name: xxxxxxxxx.dkr.ecr.ap-southeast-3.amazonaws.com/nodejs-hello-app
  newTag: latest # This tag will be replaced by the Git SHA in the pipeline
- name: xxxxxxxxx.dkr.ecr.ap-southeast-3.amazonaws.com/go-hello-app
  newTag: latest # This tag will be replaced by the Git SHA in the pipeline